// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTrS4rcYmEZRXjz9Pk9F8aMq1FakZUUkc',
    appId: '1:64178985072:web:b133897b8574184d337cb5',
    messagingSenderId: '64178985072',
    projectId: 'autohub-fda88',
    authDomain: 'autohub-fda88.firebaseapp.com',
    storageBucket: 'autohub-fda88.firebasestorage.app',
    measurementId: 'G-3GCQZW4MP0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAR4E_dTwEECUithMu5RpUu84i9ZkzGaTc',
    appId: '1:64178985072:android:3e9542bb39fbdb37337cb5',
    messagingSenderId: '64178985072',
    projectId: 'autohub-fda88',
    storageBucket: 'autohub-fda88.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHNF3dWp_H5y2O_iE9DFmLDAv6l_CWek4',
    appId: '1:64178985072:ios:49c37254a81faf34337cb5',
    messagingSenderId: '64178985072',
    projectId: 'autohub-fda88',
    storageBucket: 'autohub-fda88.firebasestorage.app',
    iosBundleId: 'com.example.autohub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHNF3dWp_H5y2O_iE9DFmLDAv6l_CWek4',
    appId: '1:64178985072:ios:49c37254a81faf34337cb5',
    messagingSenderId: '64178985072',
    projectId: 'autohub-fda88',
    storageBucket: 'autohub-fda88.firebasestorage.app',
    iosBundleId: 'com.example.autohub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTrS4rcYmEZRXjz9Pk9F8aMq1FakZUUkc',
    appId: '1:64178985072:web:8afb85f336c8840c337cb5',
    messagingSenderId: '64178985072',
    projectId: 'autohub-fda88',
    authDomain: 'autohub-fda88.firebaseapp.com',
    storageBucket: 'autohub-fda88.firebasestorage.app',
    measurementId: 'G-BK43858FTB',
  );
}
